# -*- coding: utf-8 -*-
"""Regression_metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pBvPjwR59M9cZT3iDLoPUk_omXT2-TXO
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error
import numpy as np

#real score
real_score = [90, 60, 70, 100]

#predicted output(machine gussing result)
predict_score = [85, 70, 90, 95]

mae = mean_absolute_error(real_score, predict_score)
mse = mean_squared_error(real_score, predict_score)
rmse = root_mean_squared_error(real_score, predict_score)

print("MAE : On average off by... ",mae)
print("MSE : Squred mistake value... ",mse)
print("RMSE : Final realistic error... ",rmse)